version: 0.2
phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - $(aws ecr get-login --no-include-email --region ap-south-1)
  build:
    commands:
      - echo Building the Docker image...
      - docker build -t nginx:${CODEBUILD_BUILD_NUMBER} .
      - echo Tagging the Docker image...
      - docker tag nginx:${CODEBUILD_BUILD_NUMBER} 746256143333.dkr.ecr.ap-south-1.amazonaws.com/nginx:${CODEBUILD_BUILD_NUMBER}
      - echo Pushing the Docker image to Amazon ECR...
      - docker push 746256143333.dkr.ecr.ap-south-1.amazonaws.com/nginx:${CODEBUILD_BUILD_NUMBER}
